name: BUG反馈
description: 程序出问题了
title: "[BUG]: "
labels: ["BUG"]
body:
  - type: markdown
    attributes:
      value: |
        感谢填写BUG反馈！
  - type: textarea
    id: contact
    attributes:
      label: 描述这个BUG
      description: 用详细的语言描述这个BUG是什么（发生了什么）
      placeholder: 在此描述
    validations:
      required: true
  - type: textarea
    id: step
    attributes:
      label: 怎么触发这个BUG
      description: BUG触发的流程
      placeholder: 在此描述
      value: |
        1、打开xxx
        2、点击xxx
        3、滑动xxx
        4、出现了BUG
    validations:
      required: true
  - type: input
    id: result
    attributes:
      label: 正确的结果应该是怎样？（选填）
      description: 程序正确情况下应该作出什么反应
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: 你使用的是什么系统？
      description: 选择你使用的操作系统
      options:
        - Windows
        - Linux
        - Mac-OS
      default: 0
    validations:
      required: true
  - type: upload
    id: screenshots
    attributes:
      label: 屏幕截图（选填）
      description: 如果可以，上传几张截图来补充说明
    validations:
      required: false
  - type: checkboxes
    id: asdf
    attributes:
      label: 请确认
      description: 请确认以下选项
      options:
        - label: 我使用的系统是Windows,Linux,Mac-OS三者之一(因为作者已经放弃支持各种各样的奇葩系统了)
        - label: 我使用的软件版本是最新的
        - label: 我确保没有人在issues中提到过这个问题
          required: true
